name: Root Pipeline

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  WORKSPACE: ${{ github.actor }}


jobs:
  terragrunt-plan-dev:
    name: Dev
    uses: ./.github/workflows/terragrunt-plan.yml
    with:
      ACCOUNT: account-dev
      ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      ENV: dev
      REGISTRY: ${{ env.REGISTRY }}
      IMAGE_NAME: ${{ env.IMAGE_NAME }}
      WORKSPACE: ${{ env.WORKSPACE }}
    secrets: inherit

  terragrunt-apply-dev:
    name: Dev
    uses: ./.github/workflows/terragrunt-apply.yml
    with:
      ACCOUNT: account-dev
      ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      ENV: dev
      REGISTRY: ${{ env.REGISTRY }}
      IMAGE_NAME: ${{ env.IMAGE_NAME }}
      WORKSPACE: ${{ env.WORKSPACE }}
    secrets: inherit
    needs:
      terragrunt-plan-dev

  terragrunt-plan-staging:
    name: Staging
    uses: ./.github/workflows/terragrunt-plan.yml
    with:
      ACCOUNT: account-dev
      ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      ENV: staging
      REGISTRY: ${{ env.REGISTRY }}
      IMAGE_NAME: ${{ env.IMAGE_NAME }}
      WORKSPACE: ${{ env.WORKSPACE }}
    secrets: inherit

  # terragrunt-apply-staging:
  #   name: Staging
  #   uses: ./.github/workflows/terragrunt-apply.yml
  #   with:
  #     ACCOUNT: account-dev
  #     ACCOUNT_ID: "699193863488"
  #     REGION: "ap-southeast-1"
  #     ENV: staging
  #   secrets: inherit

  terragrunt-plan-prod:
    name: Production
    uses: ./.github/workflows/terragrunt-plan.yml
    with:
      ACCOUNT: account-prod
      ACCOUNT_ID: "699193863488"
      REGION: ap-southeast-1
      ENV: prod
      REGISTRY: ${{ env.REGISTRY }}
      IMAGE_NAME: ${{ env.IMAGE_NAME }}
      WORKSPACE: ${{ env.WORKSPACE }}
    secrets: inherit

  # terragrunt-apply-prod:
  #   name: Production
  #   uses: ./.github/workflows/terragrunt-apply.yml
  #   with:
  #     ACCOUNT: account-prod
  #     ACCOUNT_ID: "699193863488"
  #     REGION: "ap-southeast-1"
  #     ENV: prod
  #   secrets: inherit
